### ISSUE TITLE
有个体验上的问题，就是有些图片，在打开相册时显示空白问题？

### ISSUE THREAD

**Issue by 377376701** [crazyandcoder/TakePhoto#1]
博主能否有好的解决方案！如下图：
![j25_1 ju ut 0 enweatzh7](https://cloud.githubusercontent.com/assets/7800300/16006150/11a2edd8-319e-11e6-8a16-532ac1ad97c8.png)

**Comment by crazyandcoder** [comment]
那是你图片本身的问题嘛？我这边打开的图片都能显示
